// Styles object (converted from CSS)
const styles = {
  body: {
    margin: 0,
    padding: 0,
    boxSizing: 'border-box',
    fontFamily: "'Roboto', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    background: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
    backgroundAttachment: 'fixed',
    color: '#333',
  },
  locationModal: {
    display: 'none',
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'rgba(0, 0, 0, 0.85)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    zIndex: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationModalShow: {
    display: 'flex',
  },
  locationModalContent: {
    background: 'linear-gradient(135deg, #1e40af 0%, #2563eb 100%)',
    borderRadius: '20px',
    padding: '2.5rem',
    maxWidth: '700px',
    width: '90%',
    maxHeight: '85vh',
    overflowY: 'auto',
    position: 'relative',
    boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
  },
  modalClose: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: '1.3rem',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    transition: 'all 0.3s',
  },
  modalCloseHover: {
    background: 'rgba(255,255,255,0.3)',
    transform: 'rotate(90deg)',
  },
  modalHeader: {
    fontSize: '2rem',
    marginBottom: '0.5rem',
    color: '#fff',
    textAlign: 'center',
  },
  modalSubtitle: {
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '1.5rem',
    textAlign: 'center',
  },
  locationSearch: {
    position: 'relative',
    marginBottom: '1.5rem',
  },
  locationSearchInput: {
    width: '100%',
    padding: '0.9rem 1rem 0.9rem 3rem',
    border: '2px solid rgba(255,255,255,0.3)',
    borderRadius: '25px',
    fontSize: '1rem',
    background: 'rgba(255,255,255,0.15)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
  },
  locationSearchInputPlaceholder: {
    color: 'rgba(255,255,255,0.7)',
  },
  locationSearchInputFocus: {
    outline: 'none',
    borderColor: 'rgba(255,255,255,0.6)',
    background: 'rgba(255,255,255,0.2)',
  },
  searchIcon: {
    position: 'absolute',
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: 'rgba(255,255,255,0.8)',
    fontSize: '1.1rem',
  },
  popularCitiesTitle: {
    fontSize: '0.9rem',
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '1rem',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    fontWeight: 600,
  },
  citiesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
    gap: '1rem',
    marginBottom: '2rem',
  },
  cityCard: {
    padding: '1.2rem',
    border: '2px solid rgba(255,255,255,0.3)',
    borderRadius: '15px',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.3s',
    background: 'rgba(255,255,255,0.1)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    fontWeight: 500,
  },
  cityCardHover: {
    borderColor: 'rgba(255,255,255,0.8)',
    background: 'rgba(255,255,255,0.25)',
    transform: 'translateY(-3px)',
    boxShadow: '0 8px 20px rgba(0,0,0,0.3)',
  },
  cityCardSelected: {
    borderColor: '#fff',
    background: 'rgba(255,255,255,0.3)',
    boxShadow: '0 8px 20px rgba(0,0,0,0.3)',
  },
  citiesList: {
    maxHeight: '200px',
    overflowY: 'auto',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '15px',
    padding: '0.5rem',
  },
  citiesListScrollbar: {
    width: '6px',
  },
  citiesListScrollbarTrack: {
    background: 'rgba(255,255,255,0.1)',
    borderRadius: '10px',
  },
  citiesListScrollbarThumb: {
    background: 'rgba(255,255,255,0.4)',
    borderRadius: '10px',
  },
  cityListItem: {
    padding: '0.9rem',
    cursor: 'pointer',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
    transition: 'background 0.2s',
    color: '#fff',
    borderRadius: '8px',
    marginBottom: '0.3rem',
  },
  cityListItemHover: {
    background: 'rgba(255,255,255,0.2)',
  },
  header: {
    background: 'rgba(255,255,255,0.95)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 4px 20px rgba(0,0,0,0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    borderBottom: '2px solid #6366f1',
  },
  headerContainer: {
    maxWidth: '1440px',
    margin: '0 auto',
    padding: '1.2rem 2rem',
    display: 'flex',
    alignItems: 'center',
    gap: '2rem',
  },
  logo: {
    fontSize: '1.8rem',
    fontWeight: 800,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    letterSpacing: '-1px',
  },
  searchContainer: {
    flex: 1,
    maxWidth: '600px',
    position: 'relative',
  },
  searchBar: {
    width: '100%',
    padding: '0.9rem 1rem 0.9rem 3rem',
    border: '2px solid #e5e7eb',
    borderRadius: '25px',
    fontSize: '0.95rem',
    transition: 'all 0.3s',
  },
  searchBarFocus: {
    outline: 'none',
    borderColor: '#6366f1',
    boxShadow: '0 0 0 3px rgba(99, 102, 241, 0.1)',
  },
  headerLocation: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    color: '#666',
    whiteSpace: 'nowrap',
  },
  headerLocationHover: {
    color: '#6366f1',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  btnSignin: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#fff',
    padding: '0.7rem 2rem',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    boxShadow: '0 4px 15px rgba(99, 102, 241, 0.3)',
    transition: 'all 0.3s',
  },
  btnSigninHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 20px rgba(99, 102, 241, 0.4)',
  },
  hamburger: {
    display: 'none',
    flexDirection: 'column',
    gap: '4px',
    cursor: 'pointer',
  },
  hamburgerSpan: {
    width: '24px',
    height: '3px',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    borderRadius: '2px',
  },
  nav: {
    background: '#fff',
    borderBottom: '1px solid #e5e7eb',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  navContainer: {
    maxWidth: '1440px',
    margin: '0 auto',
    padding: '0 2rem',
    display: 'flex',
    gap: '2.5rem',
  },
  navLink: {
    padding: '1.2rem 0',
    color: '#666',
    textDecoration: 'none',
    fontSize: '0.95rem',
    fontWeight: 500,
    borderBottom: '3px solid transparent',
    transition: 'all 0.3s',
  },
  navLinkHover: {
    color: '#6366f1',
    borderBottomColor: '#6366f1',
  },
  navLinkActive: {
    color: '#6366f1',
    borderBottomColor: '#6366f1',
    fontWeight: 600,
  },
  bannerSection: {
    maxWidth: '1440px',
    margin: '2rem auto',
    padding: '0 2rem',
  },
  bannerSlider: {
    position: 'relative',
    height: '450px',
    borderRadius: '20px',
    overflow: 'hidden',
    boxShadow: '0 10px 40px rgba(0,0,0,0.2)',
  },
  bannerSlide: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0,
    transition: 'opacity 0.5s ease-in-out',
  },
  bannerSlideActive: {
    opacity: 1,
  },
  bannerSlideImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  bannerDots: {
    position: 'absolute',
    bottom: '1rem',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: '0.5rem',
  },
  bannerDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.5)',
    cursor: 'pointer',
  },
  bannerDotActive: {
    background: '#fff',
    width: '24px',
    borderRadius: '4px',
  },
  filtersSection: {
    background: 'rgba(255,255,255,0.95)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    padding: '1.5rem 0',
    borderBottom: '1px solid #e5e7eb',
    position: 'sticky',
    top: '125px',
    zIndex: 100,
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  filtersContainer: {
    maxWidth: '1440px',
    margin: '0 auto',
    padding: '0 2rem',
    display: 'flex',
    gap: '1rem',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  filtersContainerScrollbar: {
    display: 'none',
  },
  filterChip: {
    padding: '0.6rem 1.5rem',
    background: '#fff',
    border: '2px solid #e5e7eb',
    borderRadius: '25px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    transition: 'all 0.3s',
    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
  },
  filterChipHover: {
    borderColor: '#6366f1',
    color: '#6366f1',
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.2)',
  },
  filterChipActive: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#fff',
    borderColor: 'transparent',
    boxShadow: '0 4px 15px rgba(99, 102, 241, 0.4)',
  },
  section: {
    maxWidth: '1440px',
    margin: '2.5rem auto',
    padding: '0 2rem',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
  },
  sectionTitle: {
    fontSize: '1.8rem',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  seeAll: {
    color: '#6366f1',
    textDecoration: 'none',
    fontSize: '1rem',
    fontWeight: 600,
    transition: 'all 0.3s',
  },
  seeAllHover: {
    transform: 'translateX(5px)',
  },
  moviesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: '2rem 1.5rem',
  },
  movieCard: {
    cursor: 'pointer',
    transition: 'transform 0.3s',
    background: '#fff',
    borderRadius: '15px',
    overflow: 'hidden',
    boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
  },
  movieCardHover: {
    transform: 'translateY(-8px)',
    boxShadow: '0 8px 25px rgba(0,0,0,0.15)',
  },
  moviePoster: {
    position: 'relative',
    overflow: 'hidden',
  },
  moviePosterImg: {
    width: '100%',
    aspectRatio: '2/3',
    objectFit: 'cover',
    transition: 'transform 0.5s',
  },
  movieCardHoverImg: {
    transform: 'scale(1.05)',
  },
  movieBadge: {
    position: 'absolute',
    top: '0.8rem',
    left: 0,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#fff',
    padding: '0.4rem 1rem',
    fontSize: '0.75rem',
    fontWeight: 600,
    borderRadius: '0 15px 15px 0',
    boxShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
  movieRating: {
    position: 'absolute',
    bottom: '0.8rem',
    left: '0.8rem',
    background: 'rgba(0,0,0,0.85)',
    WebkitBackdropFilter: 'blur(10px)',
    backdropFilter: 'blur(10px)',
    color: '#fff',
    padding: '0.4rem 0.8rem',
    fontSize: '0.85rem',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    fontWeight: 600,
  },
  votes: {
    fontSize: '0.7rem',
    opacity: 0.9,
    fontWeight: 400,
  },
  movieInfo: {
    padding: '1rem',
  },
  movieTitle: {
    fontSize: '1.05rem',
    fontWeight: 600,
    marginBottom: '0.4rem',
    color: '#333',
  },
  movieGenre: {
    fontSize: '0.85rem',
    color: '#666',
  },
  comingSoonBadge: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#fff',
    padding: '0.6rem',
    textAlign: 'center',
    fontSize: '0.85rem',
    fontWeight: 600,
    marginTop: '0.5rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(99, 102, 241, 0.3)',
  },
  entertainmentSection: {
    background: '#fff',
    padding: '2rem 0',
    margin: '2rem 0',
  },
  entertainmentGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '1.5rem',
  },
  entertainmentCard: {
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'transform 0.2s',
  },
  entertainmentCardHover: {
    transform: 'translateY(-4px)',
  },
  entertainmentIcon: {
    width: '100%',
    aspectRatio: 1,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '3rem',
    marginBottom: '0.8rem',
  },
  entertainmentTitle: {
    fontSize: '0.95rem',
    fontWeight: 500,
    color: '#333',
  },
  footer: {
    background: '#333',
    color: '#fff',
    padding: '3rem 2rem 1rem',
  },
  footerContainer: {
    maxWidth: '1440px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '2rem',
    marginBottom: '2rem',
  },
  footerSectionH4: {
    marginBottom: '1rem',
    fontSize: '1rem',
  },
  footerLinks: {
    listStyle: 'none',
  },
  footerLinksLi: {
    marginBottom: '0.5rem',
  },
  footerLinksA: {
    color: '#999',
    textDecoration: 'none',
    fontSize: '0.9rem',
  },
  footerLinksAHover: {
    color: '#fff',
  },
  footerBottom: {
    borderTop: '1px solid #444',
    paddingTop: '1rem',
    textAlign: 'center',
    color: '#999',
    fontSize: '0.85rem',
  },
  socialLinks: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1rem',
  },
  socialIcon: {
    width: '36px',
    height: '36px',
    background: '#444',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  socialIconHover: {
    background: '#6366f1',
  },
  responsive: {
    headerContainer: {
      padding: '1rem',
      gap: '1rem',
    },
    searchContainer: {
      display: 'none',
    },
    headerActions: {
      gap: '0.8rem',
    },
    hamburger: {
      display: 'flex',
    },
    navContainer: {
      padding: '0 1rem',
      gap: '1rem',
      overflowX: 'auto',
    },
    bannerSlider: {
      height: '250px',
    },
    section: {
      padding: '0 1rem',
    },
    moviesGrid: {
      gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
      gap: '1.5rem 1rem',
    },
    citiesGrid: {
      gridTemplateColumns: 'repeat(2, 1fr)',
    },
  },
};

export default styles;
